version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7a:1f:5f:b6:c9:ee:0c:a3:92:ef:a8:7f:16:18:9f:31"
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Compile
          command: |
            npm run build
            npm run lint
      - run:
          name: Test
          command: |
            npm test
            npm run coverage
            npm run codecov
      - run:
          name: Publish
          command: |
            git config --global user.email circleci@circleci.com
            git config --global user.name CircleCI
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            npm run lock
#            if test "$CIRCLE_BRANCH" = "master"; then npm run cd; else git push origin $CIRCLE_BRANCH; fi
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
